spring:
  zipkin:
    base-url: http://127.0.0.1:9411/  #zipkin server的请求地址
    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
  sleuth:
    sampler:
      probability: 1.0  #采样的百分比
  application:
    name: api-gateway
  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848 # 将gateway注册到nacos
    gateway:
      discovery:
        locator:
          enabled: true # 让gateway从nacos中获取服务信息
      routes:
        - id: sewage-auth
          uri: lb://sewage-auth
          order: 1
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: sewage-system
          uri: lb://sewage-system
          order: 1
          predicates:
            - Path=/sys/**
          filters:
            - StripPrefix=1
        - id: sewage-bill
          uri: lb://sewage-bill
          order: 1
          predicates:
            - Path=/bill/**
          filters:
            - StripPrefix=1
        - id: sewage-tax
          uri: lb://sewage-tax
          order: 1
          predicates:
            - Path=/tax/**
          filters:
            - StripPrefix=1
        - id: sewage-agg
          uri: lb://sewage-agg
          order: 1
          predicates:
            - Path=/agg/**
          filters:
            - StripPrefix=1
        - id: sewage-message
          uri: lb://sewage-message
          order: 1
          predicates:
            - Path=/mes/**
          filters:
            - StripPrefix=1
        - id: sewage-chat
          uri: lb://sewage-chat
          order: 1
          predicates:
            - Path=/chat/**
          filters:
            - StripPrefix=1