spring:
  zipkin:
    base-url: http://127.0.0.1:9411/  #zipkin server的请求地址
    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
  sleuth:
    sampler:
      probability: 1.0  #采样的百分比
  application:
    name: api-gateway
  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848 # 将gateway注册到nacos
    gateway:
      discovery:
        locator:
          enabled: true # 让gateway从nacos中获取服务信息
      routes:
        - id: soot-auth
          uri: lb://soot-auth
          order: 1
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: soot-system
          uri: lb://soot-system
          order: 1
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1