spring:
  zipkin:
    base-url: http://127.0.0.1:9411/  #zipkin server的请求地址
    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
  sleuth:
    sampler:
      probability: 1.0  #采样的百分比
  application:
    name: api-gateway
  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848 # 将gateway注册到nacos
    gateway:
      discovery:
        locator:
          enabled: true # 让gateway从nacos中获取服务信息
      routes:
        - id: soot-base
          uri: lb://soot-base
          order: 1
          predicates:
            - Path=/base/**
          filters:
            - StripPrefix=1
        - id: soot-data
          uri: lb://soot-data
          order: 1
          predicates:
            - Path=/data/**
          filters:
            - StripPrefix=1
        - id: soot-user
          uri: lb://soot-user
          order: 1
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1